theme: jekyll-theme-minimal
logo: https://raw.githubusercontent.com/bioboot/bimm143_W25/gh-pages/assets/img/logo.png
title: Snehita's Bioinformatics Class (BIMM 143, Winter 2025)
description: Website of Snehi's Lab Work
